### ISSUE TITLE
ecosystem

### ISSUE THREAD

**Issue by pyweeker** [kvietcong/rusty-boids#1]
Hello kvietcong,
i like your project !
i have suggestions : 
have water and ground areas , crocodile and hyppopotamus crossing areas ; food for vegans . reproduction, ageing. natural resources cycles.
season and day light cycles.

**Comment by kvietcong** [comment]
Hi PyWeeker, thank you for the compliment. I'll definitely be exploring ideas like that. Thank you for the suggestions!
